# Generated by Django 3.0.14 on 2022-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220408_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleteall',
            field=models.BooleanField(default=False),
        ),
    ]
